### PR TITLE
8333261: [repo-riscv-port-11] sun/jvm/hotspot/debugger/risv64 should be riscv64

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi,
  The package name of `RISCV64ThreadContext.java` is `sun.jvm.hotspot.debugger.riscv64`, so the directory name of `RISCV64ThreadContext.java` shoule be `src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/riscv64`, rather than `src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/risv64`.

Additional testing:

- [x] riscv64 native build
- [x] run all the jtreg tests expect for `test/hotspot/jtreg/vmTestbase/ test/hotspot/jtreg/applications/`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333261](https://bugs.openjdk.org/browse/JDK-8333261): [repo-riscv-port-11] sun/jvm/hotspot/debugger/risv64 should be riscv64 (**Bug** - P4)

### Reviewers
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)
 * [Gui Cao](https://openjdk.org/census#gcao) (@zifeihan - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/riscv-port-jdk11u.git pull/23/head:pull/23` \
`$ git checkout pull/23`

Update a local copy of the PR: \
`$ git checkout pull/23` \
`$ git pull https://git.openjdk.org/riscv-port-jdk11u.git pull/23/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 23`

View PR using the GUI difftool: \
`$ git pr show -t 23`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/riscv-port-jdk11u/pull/23.diff">https://git.openjdk.org/riscv-port-jdk11u/pull/23.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/riscv-port-jdk11u/pull/23#issuecomment-2139428624)

### CODE REVIEW

**Review by RealFYang — APPROVED** [review]
Good catch! Thanks.

**Review by zifeihan — APPROVED** [review]
Looks good, Thanks.

**Comment by sendaoYan** [comment]
Run all the jtreg tests expect for `test/hotspot/jtreg/vmTestbase/ test/hotspot/jtreg/applications/`, there two failures.

1. javax/swing/JComboBox/6632953/bug6632953.java report `malloc(): unaligned fastbin chunk detected`. I can't reproduce it now, I will check it later. I think it's unrelated to this PR.
2. java/net/MulticastSocket/Test.java report `java.net.SocketException: No such device`, it's environmental issue, unrelated to this issue.

**Comment by sendaoYan** [comment]
Thanks all for the review and sponsor.

**Pull request closed without merging**
